name: Docker Image Publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v2
      with:
        # Container registry username
        username: ${{ secrets.AZURE_ACR_USER }}
        # Container registry password
        password: ${{ secrets.AZURE_ACR_PASSWORD }}
        # Container registry server url
        login-server: ${{ secrets.AZURE_ACR }}.azurecr.io
        
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run:
        docker login ${{ secrets.AZURE_ACR }}.azurecr.io -u ${{ secrets.AZURE_ACR_USER }} -p ${{ secrets.AZURE_ACR_PASSWORD }};
        docker build . --file WebApp.Dockerfile --tag ${{ secrets.AZURE_ACR }}.azurecr.io/sample-app-aoai-chatgpt:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER_linux;
        docker tag ${{ secrets.AZURE_ACR }}.azurecr.io/sample-app-aoai-chatgpt:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER_linux ${{ secrets.AZURE_ACR }}.azurecr.io/sample-app-aoai-chatgpt:latest;
        docker push ${{ secrets.AZURE_ACR }}.azurecr.io/sample-app-aoai-chatgpt:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER_linux;
        docker push ${{ secrets.AZURE_ACR }}.azurecr.io/sample-app-aoai-chatgpt:latest;
      
